[package]
name        = "mongo_driver"
version     = "0.1.0"
authors     = ["Thijs Cadier <thijs@appsignal.com>"]
description = "Mongo Rust driver built on top of the Mongo C driver"
readme      = "README.md"
repository  = "https://github.com/thijsc/mongo-rust-driver"
keywords    = ["mongodb", "database"]
license     = "MIT"

[[test]]
name = "tests"

[dependencies]
libc        = "*"

[dependencies.bson]
git = "https://github.com/zonyitoo/bson-rs.git"

[dependencies.libmongoc-sys]
path    = "libmongoc-sys"
version = "1.1.10"
